const WishListTypes = {
  ADD_PRODUCTS_TO_WISHLIST: 'ADD_PRODUCTS_TO_WISHLIST',
  ADD_PRODUCT_TO_WISHLIST: 'ADD_PRODUCT_TO_WISHLIST',
  REMOVE_PRODUCT_FROM_WISHLIST: 'REMOVE_PRODUCT_FROM_WISHLIST',
  CLEAR_WISHLIST: 'CLEAR_WISHLIST',
};

export default WishListTypes;
